name: artic-ncov2019-medaka
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.76
  - medaka=0.11.5
  - minimap2=2.17
  - parasail-python=1.1.19
  - pysam=0.15.3
  - python=3.6.7
  - pyvcf=0.6.8
  - samtools=1.9
  - python=3
  - nodejs=12
  - bwa=0.7.17=pl5.22.0_2
  - clint=0.5.1=py36_0
  - eigen=3.2=3
  - ete3=3.1.1=py36_0
  - goalign=0.2.8=0
  - gotree=0.2.10=0
  - muscle=3.8.1551=2
  - phyml=3.3.20190909 # references etetoolkit build
  - pandas=0.23.0=py36_1
  - mafft=7.407=0
  - iqtree=1.6.12
  - datrie=0.8
  - longshot=0.4.1
  - snakemake-minimal=5.8.1
  - artic-network::rampart=1.0
  - pip
  - pip:
    - git+https://github.com/artic-network/fieldbioinformatics.git
    - git+https://github.com/artic-network/Porechop.git@v0.3.2pre
    - binlorry==1.3.0_alpha1
