name: artic-ncov2019
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic=1.1.3
  - artic-network::rampart=1.2.0
  - datrie=0.8
  - eigen=3.2=3
  - ete3=3.1.1=py36_0
  - goalign=0.2.8=0
  - gotree=0.2.10=0
  - iqtree=1.6.12
  - libdeflate=1.3
  - mafft=7.407=0
  - nodejs=12
  - phyml=3.3.20190909 # references etetoolkit build
  - python=3
  - seqtk=1.3
  - snakemake-minimal=5.8.1
  - pip
  - pip:
      - binlorry==1.3.0_alpha1
      - ont-fast5-api
